apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-realworld
spec:
  selector:
      matchLabels:
        app: node-realworld
  replicas: 3
  template:
      metadata:
        labels:
            app: node-realworld
      spec:
        containers:
        - name: node-realworld
          image: <>.azurecr.io/demo/node-express-realworld-image-demo:v1
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 3000
          livenessProbe:
            tcpSocket:
              port: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
