apiVersion: v1
kind: Service
metadata:
  name: node-realworld-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: node-realworld
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000