apiVersion: v1
kind: Service
metadata:
  name: node-realworld-internal-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.240.0.6
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: node-realworld
